### ISSUE TITLE
Promise error handling

### ISSUE THREAD

**Issue by acdlite** [neumino/thinky#187]
The following throws an error

```js
User.get(nonExistentUsername)
  .then(function(user) {});
  .catch(function(error) {});
```

The correct promise behavior is to return a rejected promise, not throw an error. A workaround is to pass an error handler to `then()` instead of using `catch()`

```js
User.get(nonExtesentUsername)
  .then(
    function(user) {},
    function(error) {}
  );
```

but this shouldn't be necessary. Either form should work.

This is a particularly nasty issue because it breaks ES7 async/await functions (which have become more common with the increasingly popularity of Babel). The error in the following example should be caught

```js
async function() {
  try {
    let user = await User.get(nonExistentUsername);
  } catch (err) {
    // handler err
  }
}
```

but instead it throws an error.

I'm not familiar with Bluebird, but maybe updating to the latest version would fix this by bringing it more in line with the ES6 promise spec?

**Comment by acdlite** [comment]
Upon further investigation, I can't reproduce this consistently... Closing for now.

**Comment by neumino** [comment]
Thinky shouldn't throw any error and only reject the promise (at least this is how it is supposed to behave).

@acdlite -- if you can reproduce it again, let me know, and I'll look again, but after a first glance, `DocumentNotFound` error are not thrown.

**Comment by vjpr** [comment]
I'm getting the same problem in Koa.

Here's my stack:
```

  Document not found: The query did not find a document and returned null in:
      at xxx/node_modules/thinky/lib/query.js:256:18
      at doNTCallback0 (node.js:415:9)
  From previous event:
      at new Promise (xxx/node_modules/thinky/node_modules/bluebird/js/main/promise.js:82:37)
      at Query._execute (xxx/node_modules/thinky/lib/query.js:265:11)
      at Query.run (xxx/node_modules/thinky/lib/query.js:63:17)
      at Object.callee$0$0$ (xxx/src/modules/user/index.js:20:48)
      at tryCatch (xxx/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (xxx/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:234:22)
      at GeneratorFunctionPrototype.Gp.(anonymous function) [as next] (xxx/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:270:19)
      at Object.fns.params.(anonymous function) (xxx/node_modules/koa-router/lib/route.js:186:15)
      at GeneratorFunctionPrototype.next (native)
      at Object.<anonymous> (xxx/node_modules/koa-router/node_modules/koa-compose/index.js:29:12)
      at GeneratorFunctionPrototype.next (native)
      at Object.dispatch (xxx/node_modules/koa-router/lib/router.js:317:14)
      at GeneratorFunctionPrototype.next (native)
      at Object.<anonymous> (xxx/node_modules/koa-mount/node_modules/koa-compose/index.js:29:12)
      at GeneratorFunctionPrototype.next (native)
      at Object.<anonymous> (xxx/node_modules/koa-mount/index.js:58:23)
      at GeneratorFunctionPrototype.next (native)
      at Object.serve (xxx/node_modules/koa-static/index.js:41:14)
      at GeneratorFunctionPrototype.next (native)
      at Object.<anonymous> (xxx/node_modules/koa-mount/index.js:52:33)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (xxx/node_modules/koa/node_modules/co/index.js:64:19)
```

**Comment by neumino** [comment]
You need to wrap your query in a try/catch.

**Comment by vjpr** [comment]
Thanks you are right!

But I did not want to have to wrap every single db call in a `try catch`.

My solution was to read this -> https://github.com/koajs/koa/wiki/Error-Handling

Which says to add the following to the top of my middleware stack:

```
app.use(function *(next) {
  try {
    yield next;
  } catch (err) {
    this.status = err.status || 500;
    this.body = err.message;
    this.app.emit('error', err, this);
  }
})
```

Problem solved!

**Comment by vjpr** [comment]
Actually what do you suggest to avoid using `try catch` in my Koa routes? 

I want to write code like this:

```
routes.get('/:user', function *(next) {
  this.user = yield User.get(this.params.user).run()
  this.assert(this.user, 404)
  this.body = this.user
})
```

Instead of adding noise with `try catch`.

**Comment by vjpr** [comment]
At the moment I am just doing this:

```
var et = e => {
  // Maybe check that its a DocumentNotFound, or else throw an error.
  return
}

var routes = new Router

routes.param('user', function *(id, next) {
  this.user = yield User.get(this.params.user).run().catch(et)
  yield next
})

routes.get('/:user', function *(next) {
  this.assert(this.user, 404)
  this.body = this.user
})
```

This lets me use the same code for getting a user, as well as `getOrCreate` - as this shouldn't short-circuit if the user doesn't exist.

**Comment by neumino** [comment]
What's wrong with the global try/catch?
It's like chaining promises and using a single error/catch which part of the reasons promises were created.

**Comment by vjpr** [comment]
If I am writing a `getOrCreate` method. I need to get the `User` and if `DocumentNotFound` then I create a new user. My previous post looks the nicest.
