### ISSUE TITLE
apply filter issue on getJoin

### ISSUE THREAD

**Issue by codedmart** [neumino/thinky#301]
Not sure if I am not doing something right but I have this apply function that works fine:
```js
_apply: function(s) {
    return s
    .filter({private: false})
    .skip(offset)
    .limit(perPage);
}
```
Now I want to filter out documents whose `deletedAt` field exists:
```js
_apply: function(s) {
    return s
    .filter(r.row.hasFields('deletedAt').not())
    .filter({private: false})
    .skip(offset)
    .limit(perPage);
}
```
and I get this error:
```
    TypeError: Uncaught error: Cannot read property 'nestingLevel' of undefined
    at Term.expr (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:2169:30)
    at Term._wrap (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:2697:34)
    at Term.merge (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:1298:64)
    at /Users/bmartin/Work/lumi/lumi-flapjack/node_modules/thinky/lib/query.js:360:35
    at Object.loopKeys (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/thinky/lib/util.js:203:16)
    at Query.getJoin (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/thinky/lib/query.js:307:8)
    at model.index (/Users/bmartin/Work/lumi/lumi-flapjack/common/crud.js:73:14)
    at Object.internals.handler (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/lib/handler.js:94:36)
    at /Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/lib/handler.js:22:22)
    at /Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/lib/request.js:321:13
    at iterate (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /Users/bmartin/Work/lumi/lumi-flapjack/node_modules/hapi/node_modules/hoek/lib/index.js:781:22
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by neumino** [comment]
You can't use `r.row` because `getJoin` injects anonymous functions and that the `_apply` method is nested.
Replacing `.filter(r.row.hasFields('deletedAt').not())` with `.filter(function(doc) { return doc.hasFields('deletedAt').not()})` seems to work for me.

I'm traveling at the moment, but there's a bug around in rethinkdbdash. It should throw "nested r.row not allowed" or something similar, not the one here.

**Comment by codedmart** [comment]
Thanks @neumino! I swear I tried that before posting but must have had a typo without noticing.
