### ISSUE TITLE
.without() fails with driver error

### ISSUE THREAD

**Issue by kheide** [neumino/thinky#316]
Hi, 

I am trying to exclude a field being returned (sensitive information) and I am trying to use the .without() function as it seems to be the cleanest method I've come across as there doesnt seem to be a .toJSON() method like mongoose and sails/waterline has. 

When I try to run the following code: 
```javascript
    Users.filter(search).without('field').getJoin().run()
```

I am given this error: 

```
Possibly unhandled ReqlDriverError: `toJSON` takes 0 argument, 1 provided after:
r.now()
    at Term._arity (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:2815:15)
    at Term.toJsonString (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:2610:14)
    at Object.stringify (native)
    at ServerResponse.json (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/express/lib/response.js:242:19)
    at ServerResponse.send (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/express/lib/response.js:151:21)
    at Users.without.getJoin.run.then.error.res.send.message (/Users/kenth/SOFTDEV/aw-dev/atwork-api/api/controllers/core/UsersController.js:37:22)
    at tryCatch1 (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/bluebird/js/main/promise.js:800:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/bluebird/js/main/promise.js:934:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/Users/kenth/SOFTDEV/aw-dev/atwork-api/node_modules/thinky/node_modules/bluebird/js/main/async.js:38:14)
    at process._tickCallback (node.js:419:13)
```

I do not have an r.now() defaults in the model as another issue has stated will throw this error.

**Comment by kheide** [comment]
getJoin() throws the error because there is a default(r.now()) in the related model.

**Comment by chippawah** [comment]
@kheide/ @neumino I think I'm getting the same error with a getJoin, can you explain what causes this?

**Comment by neumino** [comment]
If you set a default value to `r.now()` for the field `date` and retrieve a document without that field, the value will be set to `r.now()`.
Once that's done, you cannot serialize this object to JSON as `r.now()` is a ReQL term, not a JSON value.

**Comment by chippawah** [comment]
@neumino Thanks for the speedy response! I changed from using `.run()` on the query for my update to using `.execute()` I realize this means it won't validate before saving but it seems to be working fine now.
