### ISSUE TITLE
thinky 2.1.11 compatibility with nodejs 4.2.x

### ISSUE THREAD

**Issue by sikancil** [neumino/thinky#379]
**Test Environments:**
* NodeJS v4.2.1
* Hapi v11.0.3
* RethinkDB 2.1.4~0trusty (GCC 4.8.2)
* thinky v2.1.11

##### Service: **check.js**
```javascript
var Hapi = require('hapi');
var Inert = require('inert');

var Server = new Hapi.Server();

Server.connection({
	address: '0.0.0.0',
	port: 9999,
	autoListen: true
});

Server.register(Inert, function(){});

var thinky = require('thinky')({
	min:			50,
	max:			1000,
	bufferSize:	50,
	timeoutError:	1000,
	timeoutGb:	60*60*1000,
	host:			'localhost',
	port:			28015,
	authKey:		'AING#4dm1n@IS'
});
var type = thinky.type;
var Errors = thinky.Errors;

thinky.r.dbList().run().then(function(results){
	console.log(' > ', results);
}).error(console.log);

var TUsers = thinky.createModel('Users', {
	id: type.id(),
	password: type.string(),
	name: type.string(),
	groups: type.array().schema( type.string() ),
	lastseen: type.date().default( thinky.r.now() ),
	createdAt: type.date().default( thinky.r.now() )
});

Server.route([
	{
		method: ['*'],
		path: '/{params*}',
		handler: {
			directory: {
				path: process.cwd() + '/public/',
				index: true,
				listing: false,
				showHidden: false,
				redirectToSlash: true
			}
		}
	},
	{
		method: ['*'],
		path: '/thinky/test',
		handler: function($req, $reply){
			TUsers
				.run()
				.then(function(results){
					$reply({
						ok: true,
						ref: results
					});
				})
				.catch(Errors.DocumentNotFound, function(error){
					$reply({
						msg: 'Empty!',
						ref: error.message
					});
				})
				.error(function(error){
					$reply({
						msg: 'Error',
						ref: error.message
					});
				});
		}
	}
]);

Server.start(function(){
	console.log('Service was mounted to: ', Server.info.uri);
});
```

##### Documents in RethinkDB for **Users**
```javascript
[{
    "createdAt":{"$reql_type$":"TIME","epoch_time":1420203600,"timezone":"+00:00"},
    "groups":["official","users"],
    "id":"user1@check.dev",
    "lastseen":{"$reql_type$":"TIME","epoch_time":1420203600,"timezone":"+00:00"},
    "name":"User #1",
    "password":"$2a$10$jEl6DRshKRGxtD/qZeyG2.PUlOaLe7SIyC5Q7.Fghn12Wi1CzCzE."
}, {
    "createdAt":{"$reql_type$":"TIME","epoch_time":1420203600,"timezone":"+00:00"},
    "groups":["admin","official","users"],
    "id":"admin@check.dev",
    "lastseen":{"$reql_type$":"TIME","epoch_time":1420203600,"timezone":"+00:00"},
    "name":"Administrator",
    "password":"$2a$10$FhjNshUhn5gWyXnzfaNDdOE9sTmnbpsw5r0h3Kvd6rS6KS81uaw8G"
}]
```

##### Logs return from **Shell**:
```
Creating a pool connected to localhost:28015
Service was mounted to:  http://0.0.0.0:9999
Warning: a promise was created in a  handler but was not returned from it
    at Pool.getConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:72:11)
    at Pool.<anonymous> (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:405:12)
    at emitOne (events.js:77:13)
    at Pool.emit (events.js:169:7)
    at Pool.putConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:164:10)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:277:10
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Pool.createConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:197:51)
    at Pool._expandBuffer (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:311:10)
    at PoolMaster._expandAll (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:142:27)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:135:12
From previous event:
    at PoolMaster.getConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:127:12)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:146:28
From previous event:
    at Term.run (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:145:21)
    at Thinky.dbReady (/home/svc/node_modules/thinky/lib/thinky.js:70:4)
    at new Thinky (/home/svc/node_modules/thinky/lib/thinky.js:55:8)
    at module.exports (/home/svc/node_modules/thinky/lib/thinky.js:144:10)
    at Object.<anonymous> (/home/svc/check.js:30:31)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-dev/lib/wrap.js:58:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)

Warning: a promise was created in a  handler but was not returned from it
    at Pool.getConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:72:11)
    at Pool.<anonymous> (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:405:12)
    at emitOne (events.js:77:13)
    at Pool.emit (events.js:169:7)
    at Pool.putConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:164:10)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:277:10
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Pool.createConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:197:51)
    at Pool._expandBuffer (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:311:10)
    at PoolMaster._expandAll (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:142:27)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:135:12
    at PoolMaster.getConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:127:12)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:146:28
    at Term.run (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:145:21)
    at Object.<anonymous> (/home/svc/check.js:42:19)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/node-dev/lib/hook.js:43:7)
From previous event:
    at PoolMaster.getConnection (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/pool_master.js:127:12)
    at /home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:146:28
From previous event:
    at Term.run (/home/svc/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:145:21)
    at Object.<anonymous> (/home/svc/check.js:42:19)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-dev/lib/wrap.js:58:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

 >  [ 'mainsvc', 'rethinkdb', 'activities' ]
```

It's got a lot of warning output.
I got the results from ```thinky.r.dbList().run()``` in shell:
```javascript
[ 'mainsvc', 'rethinkdb', 'activities' ]
```
But, then when I open the URL: [http://localhost:9999/thinky/test] (http://localhost:9999/thinky/test)
PostMan (browser) returns:
```javascript
{
    "ok": true,
    "ref": [
    ]
}
```
meaning ```no data are returned``` from the command/query given on script, might be failed.
I just thought that might ```thinky v2.1.11``` is not compatible yet with ```NodeJS v4.2.x```.
Or please might be somebody could help me figure out this, because I wanted it able to works with latest node LTS/Stable version ```(current LTS v4.2.1)```.
I appreciate for any feedback and many thanks!

**Comment by neumino** [comment]
http://bluebirdjs.com/docs/warning-explanations.html

This is a warning. You are probably using `BLUEBIRD_WARNINGS=1` in your node environment. Closing as this is not an issue in thinky.
