### ISSUE TITLE
strange warning about startup at Model.tableReady

### ISSUE THREAD

**Issue by ityao** [neumino/thinky#385]
any idea for the strange warning ?  after I comment out some fields it go out! but whatever I recover the fields it still there every time show at the start server log!!!
```
2015-11-09 17:18: Warning: a promise was created in a  handler but was not returned from it
    at Model.tableReady (/Users/silver/program/fujin8_2016/server/node_modules/thinky/lib/model.js:202:4)
    at Function.Model.new (/Users/silver/program/fujin8_2016/server/node_modules/thinky/lib/model.js:165:11)
    at Thinky.createModel (/Users/silver/program/fujin8_2016/server/node_modules/thinky/lib/thinky.js:125:24)
    at eachInstantiatedModel (/Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/index.js:106:50)
    at /Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/node_modules/lodash/index.js:2046:14)
    at /Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/node_modules/lodash/index.js:3346:13)
    at processModels (/Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/index.js:103:27)
    at buildDictionary (/Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/node_modules/sails-build-dictionary/index.js:134:9)
    at Function.module.exports.optional (/Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/node_modules/sails-build-dictionary/index.js:160:9)
    at /Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/index.js:73:47
From previous event:
    at Hook.hook.initialize (/Users/silver/program/fujin8_2016/server/node_modules/sails-hook-thinky/index.js:60:26)
    at Hook.bound [as initialize] (/Users/silver/program/fujin8_2016/server/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/silver/program/fujin8_2016/server/node_modules/sails/lib/hooks/index.js:74:14
    at /Users/silver/program/fujin8_2016/server/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /Users/silver/program/fujin8_2016/server/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (/Users/silver/program/fujin8_2016/server/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/Users/silver/program/fujin8_2016/server/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by ityao** [comment]
set env 
"BLUEBIRD_WARNINGS": 0,
it will gone !

**Comment by ipsips** [comment]
Same here. If I create a promise in model's `ready` event callback it throws that warning

```
Model.on('ready', () => {
  thinky.r.table(Model.getTableName()).indexList().run()
}
```

**Comment by ipsips** [comment]
whereas i got no warnings with the alternative syntax:

```
Model.ready().then(() =>
  thinky.r.table(Model.getTableName()).indexList().run()
)
```
