### ISSUE TITLE
Update with saveAll doesn't remove anything when set to [].

### ISSUE THREAD

**Issue by samkelleher** [neumino/thinky#436]
The documentation describes that when passing in an array of models for a property that represents the hasMany relation, that any additions/deletions will be synced.

For example, Post A, hasMany Tags, 1, 2, and 3 under the 'tags' property.

I update, removing 3, and adding 4. The relation is supposed to be preserved.

In practice I find this not to be the case.

If I set the tags property to an empty array `[]`, no change is ever made if I saveAll().

```
Post.get('A').getJoin({tags: true})
.then((loadedPost) => {
// loadedPost.tags is [{id: 1}, {id: 2}, {id: 3}]
loadedPost.tags = [];
return loadedPost.saveAll({tags: true});
})
.then(() => {
return Post.get('A').getJoin({tags: true});
})
.then((reloadedPost) => {
// reloadedPost.tags is still [{id: 1}, {id: 2}, {id: 3}]
// I expect it to be []
});
```

This is similar to the behaviour described in #358 , modifying the relation array seems to not get updated for removals, or additions.

**Comment by neumino** [comment]
Don't you want to check `reloadedPost` instead of `loadedPost`. Things seems to work for me.

If it still doesn't work, please provide a full script that I can execute that trigger this issue.

**Comment by samkelleher** [comment]
Sorry that was a copy+paste typo, updated script.  Full example, definition, and output included below. As you can see I set the property to `[]` then do a full reload, but the data is returned unaltered.

The `Post` and `Tag` models are defined as, the `post_tag` table is automatically created:
```
        this.Post = this.database.createModel('post', {});    
        this.Tag = this.database.createModel('tag', {});    
        this.Post.belongsTo(this.Tag, 'category', 'categoryId', 'id');
        this.Tag.hasMany(this.Post, 'postsAsCategory', 'id', 'categoryId');

        this.Post.hasAndBelongsToMany(this.Tag, 'tags', 'id', 'id');
        this.Tag.hasAndBelongsToMany(this.Post, 'postsAsTag', 'id', 'id');

```

The Update script is as follows:
```
Post
            .get(idOfPostToUpdate)
            .getJoin({
                tags: true
            })
            .run()
            .then((existingPost) => {

                debug('Existing Tags', existingPost.tags);
                //existingPost.merge(updatedData);
                existingPost.tags = [];
                debug('New Tags', updatedData.tags);
                return existingPost.saveAll({tags: true});

            })
            .then((existingPost) => {
                debug(`Saved update to post ${existingPost.id}`);

                // Reload the original, to restore the joins
                // TODO: Find a more optimal way to do this.
                return Post
                    .get(existingPost.id)
                    .getJoin({
                        category: true,
                        tags: true,
                        featuredImage: true
                    })
                    .run();

            })
            .then((reloadedFinalPost) => {
                debug(`Returning reloaded post ${reloadedFinalPost.id}`);
                reply(reloadedFinalPost);
            })
            .catch((e) => {
                debug(e);
                reply(e);
            });
```

This code results in the following console output (the `.saveAll()` generates the unhandled promise warning):
```
App:UpdatePost Existing Tags +38ms [ model {
   id: 'b438fb85-0534-4ddc-82ca-47bc4102af90',
   ... },
 model {
   id: 'c2b718a2-3ca0-400c-9e5e-e3a7b865d7bc',
   ... } ]
 App:UpdatePost New Tags +1ms []
Warning: a promise was created in a handler but was not returned from it
   at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
   at Term.run (<project>/node_modules/rethinkdbdash/lib/term.js:142:15)
   at <project>/node_modules/thinky/lib/document.js:1119:78
   at Object.loopKeys (<project>/node_modules/thinky/lib/util.js:200:16)
   at model.Document._saveLinks (<project>/node_modules/thinky/lib/document.js:1029:8)
   at model.Document._saveMany (<project>/node_modules/thinky/lib/document.js:1008:10)
   at <project>/node_modules/thinky/lib/document.js:834:12
   at Object.tryCatch (<project>/node_modules/thinky/lib/util.js:60:5)
   at model.Document._onSaved (<project>/node_modules/thinky/lib/document.js:815:8)
   at <project>/node_modules/thinky/lib/document.js:790:16
   at bound (domain.js:287:14)
   at runBound (domain.js:300:12)
From previous event:
   at <project>/node_modules/thinky/lib/document.js:789:29
   at Object.tryCatch (<project>/node_modules/thinky/lib/util.js:60:5)
   at <project>/node_modules/thinky/lib/document.js:776:10
   at tryCatch1 (<project>/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)
   at Promise$_callHandler [as _callHandler] (<project>/node_modules/thinky/node_modules/bluebird/js/main/promise.js:627:13)
   at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (<project>/node_modules/thinky/node_modules/bluebird/js/main/promise.js:641:18)
   at Promise$_settlePromiseAt [as _settlePromiseAt] (<project>/node_modules/thinky/node_modules/bluebird/js/main/promise.js:800:14)
   at Promise$_settlePromises [as _settlePromises] (<project>/node_modules/thinky/node_modules/bluebird/js/main/promise.js:934:14)
   at bound (domain.js:287:14)
   at Promise.runBound (domain.js:300:12)
   at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (<project>/node_modules/thinky/node_modules/bluebird/js/main/async.js:75:12)
   at Async$consumeFunctionBuffer (<project>/node_modules/thinky/node_modules/bluebird/js/main/async.js:38:14)
   at nextTickCallbackWith0Args (node.js:452:9)
   at process._tickDomainCallback (node.js:422:13)

 App:UpdatePost Saved update to post 375e83f5-8905-40e6-85ed-f1d544ecb6ae +29ms
 App:UpdatePost Returning reloaded post 375e83f5-8905-40e6-85ed-f1d544ecb6ae +11ms
```

**Comment by neumino** [comment]
Is the first `this.Tag` a `this.Category`?

**Comment by samkelleher** [comment]
No, The 'Category' is a `Tag` type, but the application logic prevents the category also being a tag.  I.e. One tag is the 'primary category', then *any other* tag can in the 'tags'.  In my simple case, the categoryId that gets set by the category relation has an ID that is *not* also in the list of tag.

**Comment by neumino** [comment]
This script works for me:
```
var thinky = require('./lib/thinky.js')();
var type = thinky.type;
var r = thinky.r;
var Errors = thinky.Errors;
var assert = require('assert');

Post = thinky.createModel('post', {
	id: type.string(),
  categoryId: type.string(),
	content: type.string()
});
Tag = thinky.createModel('tag', {
	id: type.string(),
	tag: type.string()
});

Post.belongsTo(Tag, 'category', 'categoryId', 'id');
Tag.hasMany(Post, 'postsAsCategory', 'id', 'categoryId');

Post.hasAndBelongsToMany(Tag, 'tags', 'id', 'id');
Tag.hasAndBelongsToMany(Post, 'postsAsTag', 'id', 'id');

var post = new Post({
  content: "hello",
  tags: [
    {tag: "foo"},
    {tag: "bar"},
    {tag: "buzz"},
  ],
  category: {
    name: "Test"
  }
});

post.saveAll({tags: true, category: true}).then(function(post) {
  this.post = post;
  return Post.get(post.id).getJoin({
    tags: true
  }).run()
}).then((existingPost) => {
	existingPost.tags = [];
	return existingPost.saveAll({tags: true});
}).then((existingPost) => {
	return Post.get(existingPost.id).getJoin({
		category: true,
		tags: true,
		featuredImage: true
	}).run();
}).then((reloadedFinalPost) => {
  console.log(reloadedFinalPost)
  assert.equal(reloadedFinalPost.tags.length, 0);
  return r.getPoolMaster().drain();
}).catch((e) => {
	console.log(e);
});
```

Or am I misunderstanding what you are trying to do?

**Comment by samkelleher** [comment]
That works? Looks the same as mine except my `tag.length != 0`.  I'm gonna try run that same test case in my codebase to see if its something else, specifically looking at how the relation is removed.

The `post_tag` table has a structure of each item as below, so I am going to test to see it can successfully remove the items.
```
{
"id":  "0861ff0e-4956-4e67-978e-9116a914d68c" ,
"post_id":  "c70b6ce5-029d-4a5c-ab76-4ebdca5b22e7" ,
"tag_id":  "164d60bd-3ab5-454c-9c5b-32303b0f0210"
}
```

I'll drop back when I have worked it, thanks for your test!
😴

**Comment by samkelleher** [comment]
I've narrowed it down to https://github.com/neumino/thinky/blob/master/lib/document.js#L1117 and can see why the deletions are not occouring, but not sure the root cause.

The `keysToDelete` property does get populated, but with joined ID key values:
```
[ '375e83f5-8905-40e6-85ed-f1d544ecb6ae_b438fb85-0534-4ddc-82ca-47bc4102af90',
  '375e83f5-8905-40e6-85ed-f1d544ecb6ae_c2b718a2-3ca0-400c-9e5e-e3a7b865d7bc' ]
```

Thus, they never match the key in the table.getAll statement and are never deleted. As shown in my previous comment, the auto-generated link table gets a random ID and two `<name>_id` properties. Thus the IDs are different. I'm thinking the IDs have been created incorrectly, but this isn't thinkys fault. The database in question has been imported and was setup by a different ORM, this the ID isn't in the expected format.

Once I will set the ID to to match the format expected by thinky, the problem will go away.  I might follow up with a PR to document this ID format as part of the `hasAndBelongsToMany` in the docs.
