### ISSUE TITLE
Cannot start express.js server with Rethinkdb

### ISSUE THREAD

**Issue by hckhanh** [neumino/thinky#476]
I receive this error. I search everything but i cannot do anything to make it run

```
Creating a pool connected to localhost:28015
buffer.js:247
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:247:9)
    at Function.Buffer.from (buffer.js:115:10)
    at new Buffer (buffer.js:94:17)
    at Socket.<anonymous> (c:\Users\hoang\projects\crowdfunding-server\node_modules\rethinkdbdash\lib\connection.js:113:22)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1046:10)
```

**Comment by neumino** [comment]
I just released rethinkdbdash 2.2.20. If you update thinky, things will work again.
