### ISSUE TITLE
Error using `filter` with `getJoin`

### ISSUE THREAD

**Issue by JonDotsoy** [neumino/thinky#477]
The moment you try to generate a sentence to obtain a filtrate of a nested with `getJoin` data presented me the following error value.

**Source:**

```javascript
let getRooms = function( user, config = {} ) {
	let { order } = config

	return User
		.get( user )
		.getJoin( {
			'rooms': {
				'_apply': seq => seq
					.filter( r.row( 'status' ).eq( 'active' ) )
					.orderBy(
						r[ order ]( 'created_at' )
					)
					.limit( limit )
			},
		} )
		.run()
		.then( ( { rooms = [] } ) => rooms )
}
```

**ERROR:**

```bash
ReqlCompileError: Cannot use r.row in nested queries.  Use functions instead in:
r.table("users").get("970c6735-054c-44f6-a978-1c91960bd9e1").default(r.error("The query did not find a document and returned null."))
    .merge(r.branch(var_3.hasFields("id"), r.object("rooms", r.table("chat_room_users").getAll(var_3("id"), {
        index: "users_id"
    }).concatMap(function(var_4) {
        return r.table("chat_room").getAll(var_4("chat_room_id"), {
            index: "id"
        })
    }).filter(r.row("status").eq("active")).orderBy(r.desc("created_at"))
              ^^^^^
        .limit(30).coerceTo("ARRAY").merge(function(var_6) {
            return r.branch(var_6.hasFields("author_id"), r.table("users").getAll(var_6("author_id"), {
                index: "id"
            }).coerceTo("ARRAY").do(function(var_7) {
                return r.branch(var_7.count().eq(1), r.object("author", var_7.nth(0)), r.branch(var_7.count().eq(0), {}, r.error(r.expr("More than one element found for ").add(var_6.coerceTo("STRING")).add(r.expr("for the field ").add("author")))))
            }), {})
        })), {}))

    at Connection._processResponse (C:\Users\alfa30\Repositories\tdoee\tdoee\node_modules\rethinkdbdash\lib\connection.js:190:35)
    at Socket.<anonymous> (C:\Users\alfa30\Repositories\tdoee\tdoee\node_modules\rethinkdbdash\lib\connection.js:156:14)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

**Comment by neumino** [comment]
Don't use `r.row` in your `filter` and use a proper function
```
....filter(function(row) {
  return row('status').eq('active')
})
```

**Comment by JonDotsoy** [comment]
I great run correctly.

```javascript
....filter( room => room( 'status' ).eq( 'active' ) )
```
:smile:
