### ISSUE TITLE
Cannot serialize Joined documents using default w/ r.now()

### ISSUE THREAD

**Issue by esatterwhite** [neumino/thinky#484]
I have a simple `hasOne` relation set up and the document being joined uses `r.now`. many records were created before this default was set. When I try to serialize the object, it throws an error.

```js
Item.get('a-b-c-d').getJoin({editor:true}).then(function( e ){
   JSON.stringify( e );
})
```
```js
r.now()
    at Term._arity (/home/esatterwhite/dev/js/node-allstar/node_modules/rethinkdbdash/lib/term.js:2974:11)
    at Term.toJsonString (/home/esatterwhite/dev/js/node-allstar/node_modules/rethinkdbdash/lib/term.js:2733:10)
    at Object.stringify (native)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
    at emitKeys (readline.js:1251:14)
    at next (native)
    at ReadStream.onData (readline.js:919:36)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
``

**Comment by neumino** [comment]
What's your model definition?
Don't you have a field with a default value set to `r.now()`? If yes this is expected, you cannot serialize an ReQL query.

You can set the default value to `function() { return new Date() }` I guess.

**Comment by esatterwhite** [comment]
Yes, I followed an example in the documentation. 

You should note that in documentation. This behavior may be expected to you, I on the other hand as an end user, did not expect this

**Comment by neumino** [comment]
Link to the doc?

**Comment by esatterwhite** [comment]
http://thinky.io/documentation/schemas/

**Comment by neumino** [comment]
This is safe to do. The problem in your case is that you have a document that doesn't have this field, which means it was saved without thinky or was saved without this default field.

Once we retrieve it, we set the value to `r.now()`, and then you try to serialize it, which doesn't work as `r.now()` cannot be serialized.

**Comment by esatterwhite** [comment]
So... it isn't safe to do

**Comment by neumino** [comment]
It's not safe to update your schema in a non backward compatible way.
