### ISSUE TITLE
Error with withFields

### ISSUE THREAD

**Issue by JonDotsoy** [neumino/thinky#488]
Thinky not support the `withFields` and can not find solution.

Code:

```javascript
Post.get( id_post ).withFields( [ 'name' ] ).then( doc => res.json( { doc } ) ).catch( err => next( err ) )
```

Error: 

```
DocumentNotFoundError: The query did not find a document and returned null in:
r.table("posts").get("df25c7fe-a69f-4a70-926b-5aa546dd850c").default(r.error("The query did not find a document and returned null."))
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    .withFields(["name"])

    at Object.errors.create (node_modules\thinky\lib\errors.js:80:12)
    at node_modules\thinky\lib\query.js:200:34
    at tryCatcher (node_modules\rethinkdbdash\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules\rethinkdbdash\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (node_modules\rethinkdbdash\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (node_modules\rethinkdbdash\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (node_modules\rethinkdbdash\node_modules\bluebird\js\release\promise.js:680:18)
    at Async._drainQueue (node_modules\rethinkdbdash\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (node_modules\rethinkdbdash\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules\rethinkdbdash\node_modules\bluebird\js\release\async.js:16:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by neumino** [comment]
If you read the error, it says document not found. `get` did not return a document, hence the error. It has nothing to do with `withFields`.

**Comment by JonDotsoy** [comment]
No error persists, but does not occur using `without`.
