### ISSUE TITLE
doc._getModel is not a function

### ISSUE THREAD

**Issue by harrycch** [neumino/thinky#533]
In model:
```javascript
var Book = thinky.createModel("book", {
  id: type.string(),
  name: type.string()
});
```

In template:
```jade
form(name='book', method='post', action='/book')
  .form-group
    label Name
      input.form-control(type='text', name='name')
  input.btn.btn-success(type='submit', value='Save')
```

In controller:
```javascript
router.post('/book', function (req, res) {
  new Book(req.body).save().then(function (result) {
    console.log(result)
  }).error(
    function(err){console.error(err)}
  )
})
```

However when i submit the form, it gives a page of error:
# doc._getModel is not a function
```
TypeError: doc._getModel is not a function
    at new model (/home/TestApp/node_modules/thinky/lib/model.js:134:9)
    at /home/TestApp/routes/book.js:55:3
    at Layer.handle [as handle_request] (/home/TestApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/TestApp/node_modules/express/lib/router/route.js:131:13)
    at security.isConsoleLoggedIn (/home/TestApp/core/security.js:6:12)
    at Layer.handle [as handle_request] (/home/TestApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/TestApp/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/TestApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/TestApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/TestApp/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/TestApp/node_modules/express/lib/router/index.js:330:12)
    at next (/home/TestApp/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/TestApp/node_modules/express/lib/router/index.js:176:3)
    at router (/home/TestApp/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/TestApp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/TestApp/node_modules/express/lib/router/index.js:312:13)
    at /home/TestApp/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/TestApp/node_modules/express/lib/router/index.js:330:12)
    at next (/home/TestApp/node_modules/express/lib/router/index.js:271:10)
    at /home/TestApp/node_modules/express/lib/router/index.js:618:15
    at next (/home/TestApp/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/home/TestApp/node_modules/express/lib/router/index.js:176:3)
```

When I console.log the req.body out, I only see `{ name: "The Book" }`
And When I hard-code the json object `new Book({name: "The Book" }).save()`, it works. 

Is that a bug or should I do something on req.body?

**Comment by neumino** [comment]
Can you provide a full script that I can just run that triggers this error?

**Comment by jnsq** [comment]
Same problem for me.
A hint : i'm saving my form as multipart/form-data (sending corresponding content-type header), and multer take care of my request body.
And i also have no problem when i hard-code my printed json object.

**Comment by iulianvrz** [comment]
I encountered the same issue and fixed it by using body-parser with extended true:

```
app.use(bodyParser.urlencoded({ extended: true }));
```

**Comment by neumino** [comment]
I can't really help if I don't have a way to reproduce that.

**Comment by haydnhkim** [comment]
I have the same problem. In my case, extended options for bodyParser were not solved.
I copied the object and the problem was solved.

```
new Book(Object.assign({}, req.body)).save()
```

**Comment by Steinweber** [comment]
I've created a small example that allows you to create the error.

https://gist.github.com/Steinweber/dd6058915775beb33f7fb335391a599b

/app.js
/system/startup/startup.js
/system/demo/route.js | endpoint.js | model.js
